version: '3.8'
services:
  app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: app-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: app-dev-c
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
